### ISSUE TITLE
US04 - Create Profile

### ISSUE THREAD

**Issue by gabibguedes** [translate-me/profile#1]
Make the endpoint for creating profiles and associate it with the user.

**Tasks:**
- [x] Create profile for authors
- [ ] Create profile for translators
- [x] Associate it with the user
- [ ] Use swagger to document the endpoint

**Acceptance Criteria:**
- [ ] The user can be identified as translator or author
- [ ] The code is passing on code climate
- [ ] The endpoint is documented
